packages:
  - "playground"

onlyBuiltDependencies:
  - esbuild
  - sharp

verifyDepsBeforeRun: false
confirmModulesPurge: false
allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
